### ISSUE TITLE
Add possibility to add subcategories

### ISSUE THREAD

**Issue by FantaX1911** [P3D-Legacy/pokemon3d.net#187]
Make the structure of the resources categories have main categories and subcategories like this:

- Gamemodes
- Content Packs
  - Texture Packs
  -  Music Packs
  -  SFX Packs
  -  Sprites packs
  -  Other
- Tools
- Guides

And remove the maps category

**Comment by dsbilling** [comment]
@FantaX1911 Seems like there is missing some formatting here. Which ones should be sub-categories under what categories?

**Comment by dsbilling** [comment]
All categories are editable, so anyone with access will be able to edit these. I will swap this issue to add support for subcategories.

**Comment by dsbilling** [comment]
Code example:
```PHP
// assign "PHP" as a child of "BackEnd" category
$parent = Category::findByName('BackEnd');
$child = Category::findByName('PHP');
$parent->appendNode($child);
```
