### ISSUE TITLE
Newer Resources should be displayed first

### ISSUE THREAD

**Issue by JappaWakka** [P3D-Legacy/pokemon3d.net#211]
**Is your feature request related to a problem? Please describe.**
A: When looking for resources like contentpacks and gamemodes on the website, the resources are not sorted by last updated. Therefor newer resources can often be found down below older resources. 

**Describe the solution you'd like**
A:  Either the resources should be sorted by last updated or there should be custom sorting functionality.

**Comment by dsbilling** [comment]
Great suggestion, will implement it! 👍🏻
