### ISSUE TITLE
GameJolt account name length

### ISSUE THREAD

**Issue by Yukitty** [P3D-Legacy/pokemon3d.net#255]
Hi, uh. I'm JTE.
My Pokemon3D username is JTE.
My forum account name is JTE.
And my GameJolt username is JTE.

But https://pokemon3d.net/user/edit/profile says GameJolt usernames must be at least 4 characters long to link a GameJolt account. Uh... so I can't link JTE to JTE and use custom skins.

**Comment by dsbilling** [comment]
@Yukitty Thanks for reporting, will fix 💯

**Comment by dsbilling** [comment]
@Yukitty It is fixed now, please try again 👍🏻
