### ISSUE TITLE
Show the new resource page on the main page

### ISSUE THREAD

**Issue by JappaWakka** [P3D-Legacy/pokemon3d.net#286]
**Is your feature request related to a problem? Please describe.**
People keep checking the forums for content packs and such because that's immediately visible on the main page. 

**Describe the solution you'd like**
I'd like the new resource page visible on the main page. Preferably you would only need an account to download or upload content. Viewing should be available for everyone. 

**Describe alternatives you've considered**
I can also imagine that not everyone wants to create an account just to possibly get some contentpacks or gamemodes so you could also make downloading stuff available for everyone, even without an account. Uploading, commenting and rating should definitely require an account.

**Comment by dsbilling** [comment]
I removed the forum link in (3cc862f7) and added a link to the resources page (64b09ec5) on the main page. Currently in staging.
