### ISSUE TITLE
Longer Resource description length

### ISSUE THREAD

**Issue by jianmingyong** [P3D-Legacy/pokemon3d.net#287]
**Is your feature request related to a problem? Please describe.**
It is hard to properly describe a resource when the length is limited to 255 characters. I could probably only write 2 sentences out of it and then had to slap a README file somewhere to read more.

**Describe the solution you'd like**
Make the description length limit longer. Maybe up to 5000 characters?

**Describe alternatives you've considered**

**Comment by dsbilling** [comment]
Bumped to 5120 chars, in staging and will go into prod in next release 👍🏻
