### ISSUE TITLE
Statistics tracker

### ISSUE THREAD

**Issue by dsbilling** [P3D-Legacy/pokemon3d.net#78]
A statistics tracker with leaderboard that tracks in-game statistics, the game already tracks many of them, just need to output them on the site.

Split out of #76 by @FantaX1911

**Comment by dsbilling** [comment]
@FantaX1911 I found this last night. Is this the kind of stats you wanted?

These are the stats I can grab from the API:
- battle spot battles
- blackouts
- bug-catching contest battles
- caught pokemon
- cut used
- eggs hatched
- evolutions
- flash used
- fly used
- gts trades
- items found
- moves learned
- obtained bp
- pvp battles
- registerbattles
- ride used
- rock smash used
- safari battles
- steps taken
- strength used
- surf used
- tms\/hms used
- trades
- trainer battles
- waterfall used
- whirlpool usedwild battles
- wondertrades
- [17]medicine items used
- [2006]berries picked
- [22]evolution stones used
- [25]vitamins used
- [42]repels used
- [4]pok\u00e9 balls used
- [53]status booster used
- [85]apricorns picked

Getting the data for `eggs hatched` will return this:
```json
{
    "response": {
        "success": "true",
        "data": "72200"
    }
}
```

**Comment by FantaX1911** [comment]
Yes it is, there might be another "command?" for getting egg hatched.

**Comment by FantaX1911** [comment]
[https://i.imgur.com/YGlXyB0.png](https://i.imgur.com/YGlXyB0.png)
this is how they look in-game.

**Comment by dsbilling** [comment]
You want per user statistic? Not a page for all users?

**Comment by FantaX1911** [comment]
I would like to have personal statistics that the user can access via their own profile, in the screenshot I provided, you see 2 numbers next to every stat, the smaller number is the personal record and the bigger number is the total global record,

I would also like to have a global leaderboards that shows the current leader in each stat, not sure if you are able to do this, but I have faith in your abilities.

**Comment by dsbilling** [comment]
Added in 4.3
